server:
  port: 8082

spring:
  application:
    name: clerk
  datasource:
    url: jdbc:postgresql://localhost:5432/clerk
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

grpc:
  server:
    port: 9092
