server:
  port: 19090

spring:
  application:
    name: clerk
#  autoconfigure:
#    exclude:
#      - net.devh.boot.grpc.server.autoconfigure.GrpcServerSecurityAutoConfiguration
#      - net.devh.boot.grpc.client.autoconfigure.GrpcClientSecurityAutoConfiguration
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/clerkdb}
    driver-class-name: org.postgresql.Driver
    username: ${SPRING_DATASOURCE_USERNAME:clerk}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true

clerk:
  api:
    version: 3.2.0
    legacy-enabled: true
  llm:
    base-url: http://localhost:11434
    model: gemma3:1b
    timeout-ms: 60000
  jwt:
    accept-unsigned-tokens: true
    secret: clerk-dev-signing-key-change-me-please
  debug:
    include-stacktrace: true

grpc:
  server:
    port: 9092

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    env:
      show-values: always
    configprops:
      show-values: always